version: '3'
services:
  # app:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #   - .env
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000

  db:
    container_name: ${POSTGRES_DB}
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - nestFilmes:/var/lib/postgres/data

volumes:
  nestFilmes:
